[package]
name = "json-comments"
version = "0.1.1"
edition = "2024"
description = "Rust-backed JSON comment and trailing comma stripper"

[lib]
name = "_json_comments"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.29", features = ["extension-module"] }
# fork of json-comments-rs that handles trailing commas
json-strip-comments = "3.1.0"

[profile.release]
codegen-units = 1
debug = false
lto = "fat"
